//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by iPodWizard.rc
//
#define IDM_ABOUTBOX                    0x0010
#define ID_ABOUT                        0x0010
#define ID_TWEAKS                       17
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IPODWIZARD_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_PICTURES_DIALOG             129
#define IDD_FONTS_DIALOG                130
#define IDD_STRINGS_DIALOG              132
#define IDD_TWEAKS_DIALOG               133
#define HELPBTN_BLUE                    134
#define IDD_HELP_DIALOG                 134
#define HELPBTN_HOMESTEAD               135
#define HELPBTN_METALLIC                136
#define IDD_SCAN_DIALOG                 137
#define IDD_EDITOR_DIALOG               138
#define IDD_THEMES_DIALOG               139
#define IDD_UPDATER_DIALOG              140
#define ID_OPEN                         1000
#define IDC_FIRMWARE_COMBO              1001
#define IDC_BUTTON2                     1002
#define ID_LOAD_FIRMWARE                1002
#define IDC_UPDATE_BUTTON               1002
#define IDC_REFRESH_BUTTON              1002
#define IDC_MAKETHEME_BUTTON            1002
#define IDC_CHECKSUM1_EDIT              1003
#define IDC_IPODDRIVE_COMBO             1003
#define IDC_LOADTHEME_BUTTON            1003
#define IDC_CHECKSUM2_EDIT              1004
#define IDC_WIDTH_EDIT                  1005
#define IDC_HEIGHT_EDIT                 1006
#define IDC_BITDEPTH_EDIT               1007
#define HELPBTN_CLASSIC                 1007
#define ID_PREV_PICTURE                 1008
#define ID_NEXT_PICTURE                 1009
#define IDC_PICIDX_EDIT                 1010
#define IDC_PICTURE                     1011
#define IDC_BUTTON1                     1012
#define ID_LOAD_BITMAP                  1012
#define IDC_WRITE_FIRMWARE_BUTTON       1012
#define IDC_FIND_BUTTON                 1012
#define IDC_PROP_TAB                    1013
#define ID_SAVE_BITMAP                  1013
#define IDC_FIND_BUTTON2                1013
#define IDC_FINDNEXT_BUTTON             1013
#define IDC_FONTNAME_EDIT               1014
#define IDC_TYPE_EDIT                   1014
#define IDC_USYSINFO_BUTTON             1014
#define ID_SAVE_ALL                     1015
#define IDC_FONTZOOM                    1015
#define IDC_REFRESHDRV_BUTTON           1015
#define IDC_SCAN_PROGRESS               1016
#define IDC_FONTSIZE_EDIT               1016
#define ID_LOAD_ALL                     1016
#define IDC_FIRMWARE_LIST               1017
#define ID_SAVE_METRICS                 1017
#define IDC_PICIDX_COMBO                1018
#define ID_LOAD_METRICS                 1018
#define IDC_FONTIDX_COMBO               1019
#define IDC_FONT_LIST                   1019
#define IDC_STRING_LIST                 1020
#define IDC_GROUPIDX_COMBO              1020
#define IDC_FONTIDX_CMB                 1020
#define IDC_FIND_EDIT                   1021
#define IDC_CHARMAPIDX_COMBO            1021
#define IDC_CHAR_COMBO                  1022
#define IDC_CHANGE_EDIT                 1022
#define IDC_OFFSET1_EDIT                1023
#define IDC_ADDR_EDIT                   1023
#define IDC_OFFSET2_EDIT                1024
#define IDC_W1_EDIT                     1025
#define IDC_IDENT_EDIT                  1025
#define IDC_CHARMAPIDX_COMBO2           1026
#define IDC_CHARMAPIDX2_COMBO           1026
#define ID_SAVE_METRICS2                1027
#define ID_MAKE_FONT                    1027
#define IDC_HEX                         1028
#define ID_ZOOMIN_BUTTON                1029
#define IDC_GROUPLEN_EDIT               1032
#define IDC_GROUPSTART_EDIT             1033
#define IDC_GROUPOFFSET_EDIT            1034
#define IDC_GROUPEXPLAIN_STATIC         1035
#define ID_CHK_NEWMETRICS               1036
#define IDC_CHANGETEXT_BUTTON           1037
#define IDC_CHECKTEXT_BUTTON            1038
#define ID_APPLY_BUTTON                 1039
#define IDC_SAVECHANGES_BUTTON          1039
#define ID_VOLTAGE_CHKBOX               1040
#define IDC_LOADCHANGES_BUTTON          1040
#define ID_CPU_CHKBOX                   1041
#define IDC_STATIC_FOUND                1041
#define IDC_JUMP_BUTTON                 1041
#define ID_DEEPSLEEP_CHKBOX             1042
#define IDC_STATIC_NOTFOUND             1042
#define IDC_SFILTER_BUTTON              1042
#define ID_CACHE_CHKBOX                 1043
#define IDC_COMBO1                      1043
#define IDC_IPOD_COMBO                  1043
#define IDC_VOLUMEHACK_BUTTON           1043
#define ID_NODEEPSLEEP_CHKBOX           1044
#define ID_FINDGEN_BUTTON               1044
#define IDC_HYPERLINK                   1046
#define IDC_STATIC_FONT                 1047
#define IDC_STATIC_FIRM                 1048
#define ID_VOLUMECAP_BUTTON             1050
#define IDC_CHKWILD                     1052
#define IDC_STATIC_ZOOM                 1052
#define ID_ZOOMOUT_BUTTON               1053
#define IDC_CHKHEX                      1053
#define IDC_CHECK1                      1054
#define IDC_CHKGRID                     1054
#define IDC_EXPLAIN_BUTTON              1055
#define IDC_OPT_TAB                     1056
#define IDC_LOADGRAPHICS_BUTTON         1058
#define IDC_DELETEGRAPHIC_BUTTON        1059
#define IDC_LOADFONT_BUTTON             1060
#define IDC_DELETEFONT_BUTTON           1061
#define IDC_GRAPHICS_LIST               1062
#define IDC_LOADSCF_BUTTON              1063
#define IDC_CLEARSCF_BUTTON             1064
#define IDC_EXTRACT_BUTTON              1065
#define IDC_DELETE_BUTTON               1066
#define IDC_LOAD_BUTTON                 1067
#define IDC_WRITEALL_BUTTON             1068
#define IDC_SCFPATH                     1068
#define IDC_SCFPATH_STATIC              1068

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
