//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by iPodWizard.rc
//
#define ID_ABOUT                        0x0010
#define IDM_ABOUTBOX                    0x0010
#define ID_TWEAKS                       17
#define ID_EJECT_BUTTON                 18
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IPODWIZARD_DIALOG           102
#define IDS_UPDATE                      102
#define IDS_UPDATE_AVAILABLE            103
#define IDS_UPDATE_NO                   104
#define IDS_UPDATE_NOCHECK              105
#define IDS_APPLEWARN                   106
#define IDR_MAINFRAME                   128
#define IDD_PICTURES_DIALOG             129
#define IDD_FONTS_DIALOG                130
#define IDD_STRINGS_DIALOG              132
#define IDD_TWEAKS_DIALOG               133
#define HELPBTN_BLUE                    134
#define IDD_HELP_DIALOG                 134
#define HELPBTN_HOMESTEAD               135
#define HELPBTN_METALLIC                136
#define IDD_SCAN_DIALOG                 137
#define IDD_EDITOR_DIALOG               138
#define IDD_THEMES_DIALOG               139
#define IDR_MENU1                       139
#define IDD_UPDATER_DIALOG              140
#define IDD_OTF_DIALOG                  141
#define IDD_LAYOUT_DIALOG               142
#define IDB_BITMAP1                     144
#define IDB_LIGHTBULB                   144
#define IDD_TIP                         145
#define IDR_TIPSTXT                     146
#define IDD_PREFS_DIALOG                146
#define IDD_THEMEPREVIEWER              147
#define ID_OPEN                         1000
#define IDC_FIRMWARE_COMBO              1001
#define ID_LOAD_FIRMWARE                1002
#define IDC_REFRESH_BUTTON              1002
#define IDC_MAKETHEME_BUTTON            1002
#define IDC_TRANSLATE_BUTTON            1002
#define IDC_IPODDRIVE_COMBO             1003
#define IDC_LOADTHEME_BUTTON            1003
#define IDC_MODE_COMBO                  1004
#define IDC_THEMEPREVIEWER_BUTTON       1004
#define IDC_WIDTH_EDIT                  1005
#define ID_OPEN_FFILE                   1005
#define IDC_MAKEFULLTHEME_BUTTON        1005
#define IDC_HEIGHT_EDIT                 1006
#define IDC_GINDEX_EDIT                 1006
#define IDC_BITDEPTH_EDIT               1007
#define HELPBTN_CLASSIC                 1007
#define ID_PREV_PICTURE                 1008
#define ID_NEXT_PICTURE                 1009
#define IDC_FONTSTYLE_EDIT              1010
#define IDC_ID_EDIT                     1010
#define IDC_PICTURE                     1011
#define ID_LOAD_BITMAP                  1012
#define IDC_WRITE_FIRMWARE_BUTTON       1012
#define IDC_FIND_BUTTON                 1012
#define IDC_PROP_TAB                    1013
#define ID_SAVE_BITMAP                  1013
#define IDC_FINDNEXT_BUTTON             1013
#define IDC_WRITE2IPOD_FIRMWARE_BUTTON  1013
#define IDC_FONTNAME_EDIT               1014
#define IDC_TYPE_EDIT                   1014
#define IDC_USYSINFO_BUTTON             1014
#define ID_SAVE_ALL                     1015
#define IDC_FONTZOOM                    1015
#define IDC_SCAN_PROGRESS               1016
#define IDC_FONTSIZE_EDIT               1016
#define ID_LOAD_ALL                     1016
#define IDC_FIRMWARE_LIST               1017
#define ID_SAVE_METRICS                 1017
#define ID_LOAD_GLYPH                   1017
#define ID_COPY_IMAGE                   1017
#define IDC_PICIDX_COMBO                1018
#define ID_LOAD_METRICS                 1018
#define ID_SAVE_GLYPH                   1018
#define IDC_FONTIDX_COMBO               1019
#define IDC_FONT_LIST                   1019
#define ID_PASTE_IMAGE                  1019
#define IDC_STRING_LIST                 1020
#define IDC_GROUPIDX_COMBO              1020
#define IDC_FONTIDX_CMB                 1020
#define ID_FIND_BITMAP_RSRC             1020
#define IDC_FIND_EDIT                   1021
#define IDC_CHARMAPIDX_COMBO            1021
#define IDC_OTFFONTIDX_CMB              1021
#define ID_MULLOAD_GLYPH                1021
#define IDC_THEMEPREVIEW_BUTTON         1021
#define IDC_CHAR_COMBO                  1022
#define IDC_CHANGE_EDIT                 1022
#define IDC_STRIDX_CMB                  1022
#define IDC_OFFSET1_EDIT                1023
#define IDC_ADDR_EDIT                   1023
#define ID_MULSAVE_GLYPH                1023
#define IDC_OFFSET2_EDIT                1024
#define IDC_IDENT_EDIT                  1025
#define IDC_CHARMAPIDX2_COMBO           1026
#define IDC_BEARINGY_EDIT               1026
#define ID_MAKE_FONT                    1027
#define IDC_HEX                         1028
#define IDC_HEIGHT_TEXT                 1028
#define ID_ZOOMIN_BUTTON                1029
#define IDC_ADVANCE_EDIT                1030
#define IDC_GROUPLEN_EDIT               1032
#define IDC_GROUPSTART_EDIT             1033
#define IDC_GROUPOFFSET_EDIT            1034
#define IDC_GROUPEXPLAIN_STATIC         1035
#define ID_CHK_NEWMETRICS               1036
#define IDC_CHANGETEXT_BUTTON           1037
#define IDC_CHECKTEXT_BUTTON            1038
#define ID_APPLY_BUTTON                 1039
#define IDC_SAVECHANGES_BUTTON          1039
#define ID_VOLTAGE_CHKBOX               1040
#define IDC_LOADCHANGES_BUTTON          1040
#define ID_CPU_CHKBOX                   1041
#define IDC_STATIC_FOUND                1041
#define IDC_JUMP_BUTTON                 1041
#define ID_DEEPSLEEP_CHKBOX             1042
#define IDC_STATIC_NOTFOUND             1042
#define IDC_SFILTER_BUTTON              1042
#define IDC_SAVECHANGES_BUTTON2         1042
#define IDC_SAVEALLRESOURCES_BUTTON     1042
#define ID_CACHE_CHKBOX                 1043
#define IDC_IPOD_COMBO                  1043
#define IDC_VOLUMEHACK_BUTTON           1043
#define IDC_LOADALLRESOURCES_BUTTON     1043
#define ID_NODEEPSLEEP_CHKBOX           1044
#define ID_FINDGEN_BUTTON               1044
#define IDC_LOADCHANGES_BUTTON2         1044
#define IDC_SELECTORBAR_BUTTON          1044
#define IDC_HYPERLINK                   1046
#define IDC_STATIC_FONT                 1047
#define IDC_STATIC_FIRM                 1048
#define ID_VOLUMECAP_BUTTON             1050
#define IDC_CHKWILD                     1052
#define IDC_STATIC_ZOOM                 1052
#define ID_ZOOMOUT_BUTTON               1053
#define IDC_CHKHEX                      1053
#define IDC_CHKGRID                     1054
#define IDC_OTF_CHK                     1054
#define IDC_EXPLAIN_BUTTON              1055
#define IDC_OPT_TAB                     1056
#define IDC_LOADGRAPHICS_BUTTON         1058
#define IDC_DELETEGRAPHIC_BUTTON        1059
#define IDC_LOADFONT_BUTTON             1060
#define IDC_DELETEFONT_BUTTON           1061
#define IDC_GRAPHICS_LIST               1062
#define IDC_LOADSCF_BUTTON              1063
#define IDC_CLEARSCF_BUTTON             1064
#define IDC_EXTRACT_BUTTON              1065
#define IDC_ASSOCIATE_IPW               1065
#define IDC_RESOURCES_LIST              1065
#define IDC_DELETE_BUTTON               1066
#define IDC_TLOADRESOURCES_BUTTON       1066
#define IDC_LOAD_BUTTON                 1067
#define IDC_TDELETERESOURCE_BUTTON      1067
#define IDC_WRITEALL_BUTTON             1068
#define IDC_SCFPATH_STATIC              1068
#define IDC_EXTRACTIPOD_BUTTON          1069
#define IDC_OTF_BUTTON                  1069
#define IDC_GLYPHIDX_COMBO              1070
#define IDC_BEARINGX_EDIT               1071
#define IDC_BMP_BUTTON                  1072
#define IDC_GROUPEND_EDIT               1073
#define IDC_LANGIDX_COMBO               1074
#define IDC_ALEFT_EDIT                  1074
#define IDC_ARIGHT_EDIT                 1075
#define IDC_STATIC_LANG                 1076
#define IDC_BASELINE_EDIT               1076
#define ID_LOAD_FONT                    1077
#define ID_SAVE_FONT                    1078
#define IDC_LANGSTRING_LIST             1079
#define IDC_LOADIPODFW_BUTTON           1081
#define IDC_BUTTON3                     1082
#define IDC_SAVE_IFONT                  1082
#define IDC_RESOURCE_TREE               1083
#define IDC_RESOURCE_LIST               1084
#define IDC_STATIC_LOADINGLIST          1085
#define IDC_RADIO_STRINGVAL             1086
#define IDC_RADIO_HEXVAL                1087
#define IDC_CHK_PICSYSTEM               1087
#define IDC_RADIO_DECVAL                1088
#define IDC_BUTTON1                     1088
#define IDC_CHK_PICSYSTEM2              1088
#define IDC_MULTISAVE_GLYPH             1089
#define IDC_CHECK4UPDATES_BUTTON        1089
#define IDC_CHK_SHOWTIPS                1090
#define IDC_CHANGE_FONT_COLOR           1090
#define IDC_CHK_REFLASHIMAGE            1091
#define IDC_CHK_METRICSYSTEM            1092
#define IDC_CHK_UPDATES                 1093
#define IDC_IPODHELP_BUTTON             1094
#define IDC_RESOLUTION_COMBO            1094
#define IDC_THEMEID_BUTTON              1095
#define IDC_LAYOUT_COMBO                1095
#define IDC_MENU_COMBO                  1096
#define IDC_CHK_ALLSTRINGS              1096
#define IDC_MAINMENU_RADIO              1097
#define IDC_CHK_OTFDRAW                 1097
#define IDC_NOWPLAYING_RADIO            1098
#define IDC_CHK_LAYOUTDRAW              1098
#define IDC_LOADSCREEN_BUTTON           1099
#define IDC_LOADSCREEN_BUTTON2          1100
#define IDC_DRAWCOMBINE_CHECK           1100
#define IDC_CHK_RESOURCES               1102
#define IDC_CHK_GRAPHICS                1103
#define IDC_CHK_FONTS                   1104
#define IDC_CHK_STRINGS                 1105
#define IDC_CHK_RES_LAYOUT              1106
#define IDC_CHK_RES_TYPE                1107
#define IDC_CHK_RES_MENU                1108
#define IDC_CHK_RES_TCMD                1109
#define ST_FOOTER                       1264
#define IDB_MORE                        1266
#define ST_HEADER                       1267
#define IDC_TIP_RECT                    3001
#define IDC_TIPSTRING                   3002
#define IDC_STARTUP                     3003
#define IDC_NEXTTIP                     3004
#define CG_IDS_TIPOFTHEDAY              3104
#define CG_IDS_TIPOFTHEDAYMENU          3105
#define CG_IDS_DIDYOUKNOW               3106
#define CG_IDS_FILE_ABSENT              3107
#define CG_IDP_FILE_CORRUPT             3108
#define CG_IDS_TIPOFTHEDAYHELP          3109
#define ID_FIXCHECKSUM_FIXCHECKSUM      32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
